





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace M1CP.Feature.Accordion
{

    public partial interface IGlassBase
    {

        [SitecoreId]
        Guid Id { get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language { get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

    }

    public abstract partial class GlassBase : IGlassBase
    {

        [SitecoreId]
        public virtual Guid Id { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
    }
}
namespace M1CP.Feature.Accordion
{


    /// <summary>
    /// IAccordion_Folder Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Project/Common/Folder Types/Accordian/Accordion Folder</para>	
    /// <para>ID: 22b6c263-a731-4a0d-b6cf-7ab54cb4067f</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAccordion_FolderConstants.TemplateIdString)] //, Cachable = true
    public partial interface IAccordion_Folder : IGlassBase
    {
    }


    public static partial class IAccordion_FolderConstants
    {

        public const string TemplateIdString = "22b6c263-a731-4a0d-b6cf-7ab54cb4067f";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "Accordion Folder";



    }

}
namespace M1CP.Feature.Accordion
{


    /// <summary>
    /// IAccordion_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Project/Common/Content Types/Accordion/Accordion Section</para>	
    /// <para>ID: 533a169b-e03d-4883-801b-0ffe5373ec88</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAccordion_SectionConstants.TemplateIdString)] //, Cachable = true
    public partial interface IAccordion_Section : IGlassBase, global::M1CP.Feature.Accordion.I_Accordion_Section
    {
    }


    public static partial class IAccordion_SectionConstants
    {

        public const string TemplateIdString = "533a169b-e03d-4883-801b-0ffe5373ec88";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "Accordion Section";


        public static readonly ID Section_HeadingFieldId = new ID("5160ae13-9320-4e81-8df3-ae3b404c247b");
        public const string Section_HeadingFieldName = "Section Heading";



    }


    /// <summary>
    /// Accordion_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Project/Common/Content Types/Accordion/Accordion Section</para>	
    /// <para>ID: 533a169b-e03d-4883-801b-0ffe5373ec88</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAccordion_SectionConstants.TemplateIdString)] //, Cachable = true
    public partial class Accordion_Section : GlassBase, IAccordion_Section
    {

        /// <summary>
        /// The Section Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 5160ae13-9320-4e81-8df3-ae3b404c247b</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAccordion_SectionConstants.Section_HeadingFieldName)]
        public virtual string Section_Heading { get; set; }


    }
}
namespace M1CP.Feature.Accordion
{


    /// <summary>
    /// I_Accordion Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Feature/Accordion/_Accordion</para>	
    /// <para>ID: 78768ae2-17b3-4873-9e7f-ff0e70133db7</para>	
    /// </summary>
    [SitecoreType(TemplateId = I_AccordionConstants.TemplateIdString)] //, Cachable = true
    public partial interface I_Accordion : IGlassBase
    {
        /// <summary>
        /// The Accordion Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: e0c2ba8c-94d5-4a1f-a841-aa2824e741cc</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(I_AccordionConstants.Accordion_HeadingFieldName)]
        string Accordion_Heading { get; set; }

        /// <summary>
        /// The Count field.
        /// <para></para>
        /// <para>Field Type: Integer</para>		
        /// <para>Field ID: 791f8dba-e1b9-4aca-9751-6610fab7633c</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(I_AccordionConstants.CountFieldName)]
        int Count { get; set; }

    }


    public static partial class I_AccordionConstants
    {

        public const string TemplateIdString = "78768ae2-17b3-4873-9e7f-ff0e70133db7";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "_Accordion";


        public static readonly ID Accordion_HeadingFieldId = new ID("e0c2ba8c-94d5-4a1f-a841-aa2824e741cc");
        public const string Accordion_HeadingFieldName = "Accordion Heading";


        public static readonly ID CountFieldId = new ID("791f8dba-e1b9-4aca-9751-6610fab7633c");
        public const string CountFieldName = "Count";



    }


    /// <summary>
    /// _Accordion
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Feature/Accordion/_Accordion</para>	
    /// <para>ID: 78768ae2-17b3-4873-9e7f-ff0e70133db7</para>	
    /// </summary>
    [SitecoreType(TemplateId = I_AccordionConstants.TemplateIdString)] //, Cachable = true
    public partial class _Accordion : GlassBase, I_Accordion
    {

        /// <summary>
        /// The Accordion Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: e0c2ba8c-94d5-4a1f-a841-aa2824e741cc</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(I_AccordionConstants.Accordion_HeadingFieldName)]
        public virtual string Accordion_Heading { get; set; }

        /// <summary>
        /// The Count field.
        /// <para></para>
        /// <para>Field Type: Integer</para>		
        /// <para>Field ID: 791f8dba-e1b9-4aca-9751-6610fab7633c</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(I_AccordionConstants.CountFieldName)]
        public virtual int Count { get; set; }


    }
}
namespace M1CP.Feature.Accordion
{


    /// <summary>
    /// IAccordion Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Project/Common/Content Types/Accordion/Accordion</para>	
    /// <para>ID: 9312022f-c2d2-44b0-802d-c502ab9ae87e</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAccordionConstants.TemplateIdString)] //, Cachable = true
    public partial interface IAccordion : IGlassBase, global::M1CP.Feature.Accordion.I_Accordion
    {
    }


    public static partial class IAccordionConstants
    {

        public const string TemplateIdString = "9312022f-c2d2-44b0-802d-c502ab9ae87e";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "Accordion";


        public static readonly ID Accordion_HeadingFieldId = new ID("e0c2ba8c-94d5-4a1f-a841-aa2824e741cc");
        public const string Accordion_HeadingFieldName = "Accordion Heading";


        public static readonly ID CountFieldId = new ID("791f8dba-e1b9-4aca-9751-6610fab7633c");
        public const string CountFieldName = "Count";



    }


    /// <summary>
    /// Accordion
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Project/Common/Content Types/Accordion/Accordion</para>	
    /// <para>ID: 9312022f-c2d2-44b0-802d-c502ab9ae87e</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAccordionConstants.TemplateIdString)] //, Cachable = true
    public partial class Accordion : GlassBase, IAccordion
    {

        /// <summary>
        /// The Accordion Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: e0c2ba8c-94d5-4a1f-a841-aa2824e741cc</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAccordionConstants.Accordion_HeadingFieldName)]
        public virtual string Accordion_Heading { get; set; }

        /// <summary>
        /// The Count field.
        /// <para></para>
        /// <para>Field Type: Integer</para>		
        /// <para>Field ID: 791f8dba-e1b9-4aca-9751-6610fab7633c</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAccordionConstants.CountFieldName)]
        public virtual int Count { get; set; }


    }
}
namespace M1CP.Feature.Accordion
{


    /// <summary>
    /// I_Accordion_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Feature/Accordion/_Accordion Section</para>	
    /// <para>ID: f51fab8a-6db5-4ebb-aeb4-e40a221b0c55</para>	
    /// </summary>
    [SitecoreType(TemplateId = I_Accordion_SectionConstants.TemplateIdString)] //, Cachable = true
    public partial interface I_Accordion_Section : IGlassBase
    {
        /// <summary>
        /// The Section Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 5160ae13-9320-4e81-8df3-ae3b404c247b</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(I_Accordion_SectionConstants.Section_HeadingFieldName)]
        string Section_Heading { get; set; }

    }


    public static partial class I_Accordion_SectionConstants
    {

        public const string TemplateIdString = "f51fab8a-6db5-4ebb-aeb4-e40a221b0c55";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "_Accordion Section";


        public static readonly ID Section_HeadingFieldId = new ID("5160ae13-9320-4e81-8df3-ae3b404c247b");
        public const string Section_HeadingFieldName = "Section Heading";



    }


    /// <summary>
    /// _Accordion_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/m1/M1CP/Feature/Accordion/_Accordion Section</para>	
    /// <para>ID: f51fab8a-6db5-4ebb-aeb4-e40a221b0c55</para>	
    /// </summary>
    [SitecoreType(TemplateId = I_Accordion_SectionConstants.TemplateIdString)] //, Cachable = true
    public partial class _Accordion_Section : GlassBase, I_Accordion_Section
    {

        /// <summary>
        /// The Section Heading field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 5160ae13-9320-4e81-8df3-ae3b404c247b</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(I_Accordion_SectionConstants.Section_HeadingFieldName)]
        public virtual string Section_Heading { get; set; }


    }
}
